#!/bin/bash

TGT=~/
SRC=`pwd`
ln -s $SRC/wezterm.lua $TGT/.wezterm.lua
mkdir -p ~/.config/wezterm/colors
ln -s $SRC/sv_common.lua ~/.config/wezterm/sv_common.lua
ln -s $SRC/colors/onenord.toml ~/.config/wezterm/colors/onenord.toml

# vim: ai ts=2 sw=2 et sts=2 ft=s
