font_family          ComicShannsMono Nerd Font
font_size            14.0

background_opacity   0.9

remember_window_size  yes
initial_window_width  640
initial_window_height 400
#linux_display_server  x11
#hide_window_decorations no

# kitty theme kittn is set by running
#    kitty +kitten themes --reload-in=parent Catppuccin-Frappe

# BEGIN_KITTY_THEME
# Catppuccin-Frappe
include current-theme.conf
# END_KITTY_THEME
