#
# override only what is needed from /etc/xdg/fuzzel/fuzzel.ini
#

font=ComicShannsMono Nerd Font:weight=bold:size=14
dpi-aware=no
terminal=foot
anchor=center
lines=20

include=~/.config/fuzzel/frappe_green.ini

[border]
width=2
radius=8

