#
# override only what is needed from /etc/xdg/fuzzel/fuzzel.ini
#
font=ComicShannsMono Nerd Font:weight=bold:size=12
dpi-aware=auto
terminal=foot

[colors]
# - catppuccin frappe pink colors
background=303446dd
text=c6d0f5ff
prompt=b5bfe2ff
placeholder=838ba7ff
input=c6d0f5ff
match=f4b8e4ff
selection=626880ff
selection-text=c6d0f5ff
selection-match=f4b8e4ff
counter=838ba7ff
border=f4b8e4ff

# - catppuccin frappe green
#background=303446dd
#text=c6d0f5ff
#prompt=b5bfe2ff
#placeholder=838ba7ff
#input=c6d0f5ff
#match=a6d189ff
#selection=626880ff
#selection-text=c6d0f5ff
#selection-match=a6d189ff
#counter=838ba7ff
#border=a6d189ff

# - catppuccin latte pink
#background=eff1f5dd
#text=4c4f69ff
#prompt=5c5f77ff
#placeholder=8c8fa1ff
#input=4c4f69ff
#match=ea76cbff
#selection=acb0beff
#selection-text=4c4f69ff
#selection-match=ea76cbff
#counter=8c8fa1ff
#border=ea76cbff
