#
# override only what is needed from /etc/xdg/fuzzel/fuzzel.ini
#

font=ComicShannsMono Nerd Font:weight=bold:size=12
dpi-aware=auto
terminal=foot
anchor=top

include=~/.config/fuzzel/latte_green.ini

[border]
width=3

