# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
  output_format = "i3bar"
  interval = 5
  colors = false
  color_bad      = "#990000"
  color_degraded = "#b89a7c"

  # set colors=true above and uncomment what you want below
  # dark mint
  color_good     = "#9ab87c"
  # catppuccin
  #color_good     = "#669966"
  # mint-x
  #color_good     = "#345217"
}


order += "wireless wlp0s20f3"
order += "memory"
order += "load"
order += "battery all"
order += "tztime local"

wireless wlp0s20f3 {
  format_up = " %quality"
  format_down = "  down"
}

memory {
  format = "⧯ %used"
}
battery all {
  integer_battery_capacity = true
  status_chr = " "
  status_bat = " "
  status_full = " " 
  low_threshold = 30
  threshold_type = percentage
  format = "%status %percentage"
}


tztime local {
  format = "  %m/%d %H:%M "
}

cpu_usage {
  format = "  %usage "
}

load {
  format = "  %5min "
}
