#!/usr/bin/env bash
# Maintained in linux-config.org
pkill swayidle
exec swayidle -w \
  timeout ${SWAYIDLEHOOK_BLANK:-3600} 'sway-lock-utils blank' \
  resume 'sway-lock-utils unblank' \
  timeout ${SWAYIDLEHOOK_LOCK:-14400} 'sway-lock-utils lock' \
  resume 'sway-lock-utils unblank' \
  timeout ${SWAYIDLEHOOK_SUSPEND:-0} 'sway-lock-utils suspend' \
  resume 'sway-lock-utils unblank' \
  lock 'sway-lock-utils lock' \
  unlock 'sway-lock-utils unblank' \
  after-resume 'sway-lock-utils unblank' \
  before-sleep 'sway-lock-utils lock'

# every idle
# 1 second - unblank on keypress; to recover from wlogout blank
# 10 second - blank if swaylock is running
#     timeout 1 '' resume 'sway-lock-utils unblank' \
#     timeout 10 'pidof swaylock && sway-lock-utils blank'  resume 'sway-lock-utils unblank' \
