
# Ring the bell if any background window rang a bell
set -g bell-action any
# Mouse to resize and copy is useful
set -g mouse on

# Prefix C-a - closer to left hand than C-b
unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind a last-window
bind c new-window -c "#{pane_current_path}"

# Split vertical | (without shift) 
bind-key \\ split-window -h -p 50 -c "#{pane_current_path}"
# Split horizontal -
bind-key - split-window -p 50 -c "#{pane_current_path}"

# Panes and windows start at 1 and not 0
set -g base-index 1
setw -g pane-base-index 1

# Pane resize in all four directions using vi bindings.
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind-key ^D detach-client

# easier copy ops
setw -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @catppuccin_flavor "frappe"
set -g @catppuccin_status_left_separator "█"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""

set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{continuum_status}"
set -ag status-right "#{E:@catppuccin_status_host}"

run '~/.config/tmux/plugins/tpm/tpm'
