# -*- conf -*-
font=ComicShannsMono Nerd Font:size=12,monospace:size=12
include=/usr/share/foot/themes/catppuccin-frappe
dpi-aware=yes
initial-window-size-chars=120x48

[csd]
color=ff2d2821
button-color=ffebffec
border-width=1
border-color=ff000000

[colors]
alpha=1.0

# vim: ft=dosini
