# -*- conf -*-
font=ComicShannsMono Nerd Font:size=16,JetBrains Mono:size=16:monospace:size=16
include=/usr/share/foot/themes/catppuccin-frappe
dpi-aware=no
initial-window-size-chars=100x36
#initial-window-size-pixels=640x400
#initial-window-size-chars=120x36

[csd]
size=24
color=ff2c313c
button-color=ffebffec
button-width=24
border-width=1
border-color=ff000000

[colors]
alpha=0.95

# vim: ft=dosini
