# -*- conf -*-
font=ComicShannsMono Nerd Font:size=14,JetBrains Mono:size=14:monospace:size=14
include=/usr/share/foot/themes/catppuccin-frappe
dpi-aware=yes
initial-window-size-chars=100x36
#initial-window-size-pixels=640x400
#initial-window-size-chars=120x36

[csd]
color=ff2d2821
button-color=ffebffec
border-width=1
border-color=ff000000

[colors]
alpha=0.95

# vim: ft=dosini
